apiVersion: v2
name: website-php
description: Common website on PHP engine, using Nginx and PHP-FPM in single container

type: application
version: 0.2.1
appVersion: "latest"

annotations:
  category: Website

dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.3.0
- name: mariadb
  condition: mariadb.enabled
  version: 10.0.3
  repository: https://charts.bitnami.com/bitnami
- name: phpmyadmin
  condition: phpmyadmin.enabled
  version: 9.0.9
  repository: https://charts.bitnami.com/bitnami

home: https://github.com/murz-helm-charts/website-php
#icon: https://bitnami.com/assets/stacks/wordpress/img/wordpress-stack-220x234.png
keywords:
  - php
  - website
  - php-fpm
  - fpm-nginx
maintainers:
  - email: MurzNN@gmail.com
    name: Alexey Murz Korepov
sources:
  - https://github.com/murz-helm-charts/website-php
  - https://github.com/Murz-Containers/fpm-nginx
