apiVersion: v2
name: website-php
description: Common website on PHP engine, using Nginx and PHP-FPM in a single container
type: application
version: 0.3.0
appVersion: 0.1.1

maintainers:
  - name: Alexey Murz Korepov
    email: MurzNN@gmail.com

dependencies:
  - name: common
    version: 2.3.0
    repository: https://bjw-s.github.io/helm-charts
  - name: mariadb
    condition: mariadb.enabled
    version: 14.1.4
    repository: https://charts.bitnami.com/bitnami
  - name: phpmyadmin
    condition: phpmyadmin.enabled
    version: 13.1.2
    repository: https://charts.bitnami.com/bitnami
home: https://github.com/murz-helm-charts/website-php
keywords:
  - php
  - website
  - php-fpm
  - fpm-nginx
sources:
  - https://github.com/murz-helm-charts/website-php
  - https://github.com/Murz-Containers/fpm-nginx
