#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/master/charts/stable/common/values.yaml
#

siteName: php-website

hosts:
  - example.com
  - www.example.com
  - example2.com
  - subdomain.example.com

subDirectory: web

persistence:
  data:
    enabled: true
    accessMode: ReadWriteMany
    mountpath: /data
    size: 2Gi

service:
  main:
    ports:
      http:
        port: 80

image:
  # -- image repository
  repository: murznn/drupal-fpm-nginx
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: IfNotPresent


ingress:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx

    # to prevent error: upstream sent too big header while reading response header from upstream
    nginx.ingress.kubernetes.io/proxy-buffer-size: 10k

    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"

    # cert-manager.io/cluster-issuer: "letsencrypt-prod"

mariadb:
  # image:
  #   debug: true
  auth:
    username: user
    password: passw0rd
    rootPassword: superPassw0rd
  primary:
    persistence:
      size: 1Gi
