env:
  DATABASE_NAME: my_database
  DATABASE_USERNAME: root
  DATABASE_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: "{{ .Release.Name }}-mariadb"
        key: mariadb-root-password
  DATABASE_HOST: "{{ .Release.Name }}-mariadb"
  DATABASE_TYPE: mysql

controllers:
  main:
    containers:
      main:
        image:
          repository: murznn/website-php
          tag: v0.1.1

service:
  main:
    ports:
      http:
        port: 80

ingress:
  main:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/secure-backends: 'false'
      # to prevent error: upstream sent too big header while reading response header from upstream
      nginx.ingress.kubernetes.io/proxy-buffer-size: 100k
      nginx.ingress.kubernetes.io/proxy-connect-timeout: '600'
      nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '600'

persistence:
  website:
    enabled: true
    # Override this to ReadWriteOnce if cluster doesn't support ReadWriteMany.
    # This will decrease scaling by limiting the max number of PHP pods to 1.
    accessMode: ReadWriteMany
    size: 1Gi
    # See example here https://github.com/bjw-s/helm-charts/blob/fbeaa67f7d75a6f2c35c77a5e17bf129360aed17/charts/library/common/values.yaml#L656
    advancedMounts:
      main:
        main:
          - path: /website

  nginx:
    enabled: true
    type: configMap
    name: "{{ .Release.Name }}-config" # tpl conversion enabled in common.yaml
    advancedMounts:
      main:
        main:
          - path: "/etc/nginx/conf.d/default.conf"
            readonly: true
            subPath: nginx-default.conf
  php:
    enabled: true
    type: configMap
    name: "{{ .Release.Name }}-config" # tpl conversion enabled in common.yaml
    advancedMounts:
      main:
        main:
          - path: "/usr/local/etc/php/conf.d/zz_site.ini"
            readonly: true
            subPath: php.ini
