siteName: php-website

subDirectory: web

hosts:
  - example.com
  - www.example.com
  - example2.com
  - subdomain.example.com

persistence:
  size: 2Gi

ingress:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx

    # to prevent error: upstream sent too big header while reading response header from upstream
    nginx.ingress.kubernetes.io/proxy-buffer-size: 10k

    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"

    cert-manager.io/cluster-issuer: "letsencrypt-prod"

mariadb:
  # image:
  #   debug: true
  auth:
    username: user
    password: passw0rd
    rootPassword: superPassw0rd
  primary:
    persistence:
      size: 1Gi
