#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/master/charts/stable/common/values.yaml
#

hosts:
  - example.com
  - www.example.com
  - example2.com
  - subdomain.example.com

# subDirectory: web

persistence:
  website:
    enabled: true
    accessMode: ReadWriteMany
    size: 2Gi
    mountPath: "/var/www/html"
  nginx:
    enabled: true
    type: configMap
    name: "{{ .Release.Name }}-config" # tpl conversion enabled in common.yaml
    mountPath: "/etc/nginx/conf.d/default.conf"
    subPath: nginx-default.conf
  php:
    enabled: true
    type: configMap
    name: "{{ .Release.Name }}-config" # tpl conversion enabled in common.yaml
    mountPath: "/usr/local/etc/php/conf.d/zz_site.ini"
    subPath: php.ini

service:
  main:
    ports:
      http:
        port: 80

image:
  # -- image repository
  repository: murznn/website-php
  # -- image tag
  # tag: latest
  tag: v0.1.1
  # -- image pull policy
  pullPolicy: IfNotPresent

env:
  DATABASE_NAME: my_database
  DATABASE_HOST: "{{ .Release.Name }}-mariadb" # tpl conversion enabled in common.yaml
  DATABASE_USERNAME: user
  DATABASE_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: "{{ .Release.Name }}-mariadb" # tpl conversion enabled in common.yaml
        key: mariadb-password
  DATABASE_PORT: "3306"

ingress:
  main:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      kubernetes.io/ingress.class: nginx

      # to prevent error: upstream sent too big header while reading response header from upstream
      nginx.ingress.kubernetes.io/proxy-buffer-size: 100k

      nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"

      # cert-manager.io/cluster-issuer: "letsencrypt-prod"

mariadb:
  # Ref: https://github.com/bitnami/charts/blob/master/bitnami/mariadb/values.yaml
  enabled: true
  # image:
  #   debug: true
  auth:
    username: user
    password: passw0rd
    rootPassword: superPassw0rd
  primary:
    persistence:
      size: 1Gi

# Optionally add phpmyadmin instance to manage database
phpmyadmin:
  enabled: false
  # Ref: https://github.com/bitnami/charts/blob/master/bitnami/phpmyadmin/values.yaml
