apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
data:
  nginx-default.conf: |-
    {{- tpl (.Files.Get "files/nginx-default.conf.gotmpl") . | nindent 4 }}
