apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
data:
  nginx-default.conf: |-
    {{- .Files.Get "files/nginx-default.conf" | nindent 4 }}
