apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          # image: bkuhl/fpm-nginx:7.3
          image: murznn/drupal-fpm-nginx:latest
          ports:
            - containerPort: 80
          envFrom:
          - secretRef:
              name: {{ .Release.Name }}
          env:
            - name: APP_ENV
              value: dev
              # value: prod
          volumeMounts:
            - mountPath: "/var/www/html"
              name: data
            - mountPath: "/etc/nginx/conf.d/default.conf"
              name: nginx-config-default
              subPath: nginx-default.conf
      volumes:
        - name: nginx-config-default
          configMap:
            name: {{ .Release.Name }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}
