apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  DATABASE_TYPE: mysql
  DATABASE_PORT: '3306'
  DATABASE_HOST: {{ .Release.Name }}-mariadb
  DATABASE_NAME: my_database
  DATABASE_USERNAME: {{ .Values.mariadb.auth.username }}
  DATABASE_PASSWORD: {{ .Values.mariadb.auth.password }}
